candidate_fields = [
    "address",
    "address2",
    "city",
    "state",
    "country",
    "postalCode",
    "email",
    "firstName",
    "lastName",
    "workStatus",
]

application_fields = [
    "disposition",
    "gender",
    "jobviteChannel",
    "race",
    "sourceType",
    "veteranStatus",
    "workflowState",
    "workflowStateEId",
]

job_fields = [
    "department",
    "jobType",
    "location",
    "postingType",
    "requisitionId",
    "title",
]

custom_fields = [
    "when_are_you_available_to_begin_work",
    "how_did_you_hear_about_kipp",
    "are_you_a_former_or_current_kipp_employee",
    "are_you_an_alumnus_of_a_kipp_school",
    "how_many_years_of_fulltime_classroom_teaching_experience_do_you_have_not_including_student_teaching_internships_tutoring_or_volunteer_work",
    "for_your_next_position_what_would_be_your_desired_salary_range",
    "if_you_have_completed_a_teacher_licensure_program_please_indicate_what_type_of_program",
    "kipp_has_schools_located_in_different_parts_of_the_bay_area__please_select_your_geographic_preferences",
    "please_indicate_the_specific_grade_levels_you_would_like_to_teach",
    "please_indicate_the_specific_subject_areas_you_would_like_to_teach",
    "do_you_hold_a_valid_teacher_certification",
    "do_you_speak_spanish",
    "do_you_speak_a_language_other_than_english_or_spanish",
    "please_specify_which_language",
    "application_owner",
    "pay_type",
    "fte",
    "assigned_work_location",
    "have_you_applied_to_other_kipp_regions_besides_the_bay_area",
    "credentialing_score",
    "how_many_years_of_fulltime_work_experience_do_you_have",
    "paycom_job_title",
    "equipment_needed",
    "likelihood_of_hire",
    "shared_with_kipp_bayview_academy_middle",
    "shared_with_kipp_bayview_elementary",
    "shared_with_kipp_bridge__middle",
    "shared_with_kipp_excelencia",
    "shared_with_kipp_heartwood",
    "shared_with_kipp_heritage",
    "shared_with_kipp_king",
    "shared_with_sf_college_prep",
    "shared_with_ksjc",
    "shared_with_summit",
    "shared_with_valiant",
    "shared_with_kipp_bridge__elementary",
    "shared_with_navigate",
    "shared_with_sf_bay",
    "shared_with_prize",
]

column_map = {
    "are_you_a_former_or_current_kipp_employee": "formerOrCurrentKIPP",
    "are_you_an_alumnus_of_a_kipp_school": "KIPPAlumni",
    "do_you_hold_a_valid_teacher_certification": "validTeacherCert",
    "do_you_speak_a_language_other_than_english_or_spanish": "otherLanguageSpeaker",
    "do_you_speak_spanish": "spanishSpeaker",
    "for_your_next_position_what_would_be_your_desired_salary_range": "desiredSalary",
    "have_you_applied_to_other_kipp_regions_besides_the_bay_area": "otherKIPPRegions",
    "how_did_you_hear_about_kipp": "howDidYouHear",
    "how_many_years_of_fulltime_classroom_teaching_experience_do_you_have_not_including_student_teaching_internships_tutoring_or_volunteer_work": "teachingExperience",
    "how_many_years_of_fulltime_work_experience_do_you_have": "yrsExperience",
    "if_you_have_completed_a_teacher_licensure_program_please_indicate_what_type_of_program": "teacherLicensureProgram",
    "kipp_has_schools_located_in_different_parts_of_the_bay_area__please_select_your_geographic_preferences": "geoPreference",
    "please_indicate_the_specific_grade_levels_you_would_like_to_teach": "gradePref",
    "please_indicate_the_specific_subject_areas_you_would_like_to_teach": "subjectPref",
    "please_specify_which_language": "otherLanguageSpoken",
    "when_are_you_available_to_begin_work": "workStartAvailability",
    "shared_with_kipp_bayview_academy_middle": "sharedBayview",
    "shared_with_kipp_bayview_elementary": "sharedBayviewES",
    "shared_with_kipp_bridge__middle": "sharedBridgeUpper",
    "shared_with_kipp_excelencia": "sharedExcelencia",
    "shared_with_kipp_heartwood": "sharedHeartwood",
    "shared_with_kipp_heritage": "sharedHeritage",
    "shared_with_kipp_king": "sharedKing",
    "shared_with_sf_college_prep": "sharedSFCP",
    "shared_with_ksjc": "sharedSJC",
    "shared_with_summit": "sharedSummit",
    "shared_with_valiant": "sharedValiant",
    "shared_with_kipp_bridge__elementary": "sharedBridgeLower",
    "shared_with_navigate": "sharedNavigate",
    "shared_with_sf_bay": "sharedSFBay",
    "shared_with_prize": "sharedPrize",
}
